version: '3.7'

services:

  sample:
    container_name: myapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '2999:2999'
    environment:
      - NODE_ENV=development